apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-config
  namespace: ${APP_NAME}
  labels:
    app: ${APP_NAME}
data:
  BIND_PORT: "3001"
  NODE_ENV: "production"
  SUPABASE_URL: "${SUPABASE_URL}"
  SUPABASE_KEY: "${SUPABASE_KEY}"
  JWT_SECRET: "${JWT_SECRET}"
